### ISSUE TITLE
Support for $or function

### ISSUE THREAD

**Issue by tribet84** [pbatey/query-to-mongo#12]
I'd like to have support for logical or operation.

Kind regards,
R

**Comment by pbatey** [comment]
Can you write up what you think the query-string might look like? I'm wondering if you are thinking of the simple case for multiple matches on a single value ($in) which is already supported: ?tag=one&tag=two

**Comment by tribet84** [comment]
Not exactly, I'd like to generate _or statements_ like using the [$or](https://docs.mongodb.com/manual/reference/operator/query/or/) operator. The $in operator is ok when you want to include different **values**, like a bunch of Ids but I want to define multiple **conditions**.

Imagine I want to find something based on three parameters: a, b and c. Parameter 'a' is mandatory, it needs to appear but parameter 'b' and 'c' are optional. 
Something like this:

```
db.getCollection('products').find({ 
   $or: [
    { category: "Bazar y hogar", subCategory: "Aire libre y jardín"},
    { category: "Bazar y hogar", subCategory: "Bazar"}
    ]
})
```

**Comment by pbatey** [comment]
I'm not sure that query-to-mongo is the right thing for you. It's meant to gently extend http query strings by adding comparison operators (like > < >=, etc) and handle some standard options (like limit, offset).

I think for more complicated queries you'd be better off posting the query as a json object.

```
var express = require('express');
var app = express();
var bodyParser = require('body-parser')
app.use(bodyParser.json())
var mongoskin = require('mongoskin')
var db = mongoskin.db('mongodb://localhost:27027/mydb')
var collection = db.collection('mycollection')

app.post('/complex-search', function(req, res, next) {
  var query = req.body;
  var options = { limit: req.query.limit, offset: req.query.offset };
  collection.find(query, options).toArray(function(e, results) {
    if (e) return next(e)
    res.send(results)
  })
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```
