### ISSUE TITLE
Filtering "not contains" string

### ISSUE THREAD

**Issue by fox1t** [pbatey/query-to-mongo#19]
Hi, i was trying to filter out all of the documents that doesn't contains a specified string.
Let's take for example `SKU!=/.*aboca*./i` that produces `{"SKU":{"$ne":"/.*aboca*./i"}` mongo filter.
Of course, mongo throws error "Can't have regex as arg to $ne." because it wants $not operator when using regex.
Is it possible to filter "not contains" with regex right now? If it is not, do you need help to implement it?
P.S: i saw that there is not "$not" anywhere in the code.

**Comment by fox1t** [comment]
first fixes on #20 
I tried to use your coding style.
Added 3 more tests for RegExp case.

**Comment by pbatey** [comment]
merged #20
