### ISSUE TITLE
URL encoded multiple negations not working as expected

### ISSUE THREAD

**Issue by fishbeet** [pbatey/query-to-mongo#21]
Hi,
I have a use case where I need multiple url-encoded negations. In your docs these should be translated to : "Multiple not-equals comparisons are merged into a $nin operator. For example, id!=a&id!=b yields {id:{$nin:['a','b']}}."

This is not the case when they are url-encoded.

It works for single url-encoded negations e.g.:
?status=%21test translates to criteria: { status: { '$ne': 'test' }

Two negations translate to $in instead of $nin:
?status=%21test&status=%21test2 translates to criteria: { status: { '$in': [ '!test', '!test2' ] } } which is quite different to the expected { status: { '$nin': [ 'test', 'test2' ] } } and does not work.

Would it be possible to change it so that multiple url-encoded negations are translated to $nin as well?

Thanks.

**Comment by pbatey** [comment]
This is related to the difference between `!=` and `=!` in the query parameters. Currently, query-to-mongo understands _not-equal_ but doesn't understand _equals-not_.

**Comment by pbatey** [comment]
Another way to specify multiple negative values is with a comma-separated list `?status!=test,test2`

**Comment by pbatey** [comment]
Still investigating...
