### ISSUE TITLE
Commas in regex

### ISSUE THREAD

**Issue by martinszy** [pbatey/query-to-mongo#24]
When dedocing /word,word/i I get $in["/word","word/i"] instead of a regex.

Can you help me?

**Comment by pbatey** [comment]
Looks like the comma is causing the problem. I’ll take a look and see what
I can do.

**Comment by martinszy** [comment]
Hey thanks, this is now implemented in our provider filter here: https://www.quienesquien.wiki/contratos/
And in the API, docs in english here: https://quienesquienapi.readthedocs.io/en/latest/ (spanish version is more up-to-date)
