### ISSUE TITLE
Getting defaultKeywords is not defined

### ISSUE THREAD

**Issue by TimLavelle** [pbatey/query-to-mongo#31]
I've upgraded my app to NextJS 13.4.7 and still using q2m v 0.10.2 and in my API routes, I am now getting errors stating
 `error ReferenceError: defaultKeywords` is not defined and it references `/query-to-mongo/index.js:204`

This is my code:
```
var query = q2m(request.url)
let dist = await db
    .collection(table)
    .find(query.criteria, query.options)
    .sort({ name: 1 })
    .toArray();

```

Not sure if you've tested with Next 13, but just wanted to report it just in case.

**Comment by pbatey** [comment]
Thanks for pointing this out - I added some eslint to catch this type of issue in the future. It should be fixed in [v0.11.2](https://github.com/pbatey/query-to-mongo/releases/tag/v0.11.2).
