### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by jcarloslopez** [pbatey/query-to-mongo#8]
Current npm version doesn't have the merged pull requests.

Could you please update it?

**Comment by pbatey** [comment]
I see no [open pull requests](https://github.com/pbatey/query-to-mongo/pulls?q=is%3Aopen+is%3Apr) as of 2016-04-03. Can you provide a link to the pull request you are referring to?

**Comment by pbatey** [comment]
doh! I now see what you meant. npm (www.npmjs.com) is pointing to version 0.1.0, but the latest version in github is 0.5.0. Working on it...

**Comment by pbatey** [comment]
Thanks for the feedback - npm now shows version 0.5.1.

The problem was that I wasn't updating the version in package.json, or performing "npm publish".
